/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "simp.h"
#include<math.h>
#define True 1
#define False 0 
int isPrime(int input){
    int i;
    int prime = TRUE;
    if(input == 2){
        return TRUE;
    }
    if(input%2 == 0 || input <= 1){
        prime = FALSE;
    } else {
        for(i=3; i<=sqrt(input); i+=2){
            if(input%i == 0){
                prime = FALSE;
            }
        }
    }
    return prime;
}

int nextPrime(int input){
    int number = input+1;
    while(!isPrime(number)){
        number ++;
    }
    return number;
}

int *
next_prime_1_svc(operands *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
    result = nextPrime(argp->x);

	return &result;
}
