/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "simp.h"


int 
simp_prog_1(char *host,int number)
{
    struct timeval tv;
	CLIENT *clnt;
	int  *result_1;
	operands  next_prime_1_arg;
    next_prime_1_arg.x = number;

#ifndef	DEBUG
	clnt = clnt_create (host, SIMP_PROG, SIMP_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    tv.tv_sec = 60 ;
    tv.tv_usec = 0;
    clnt_control(clnt, CLSET_TIMEOUT,&tv);

	result_1 = next_prime_1(&next_prime_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    return *result_1;
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host value\n", argv[0]);
		exit (1);
	}
	host = argv[1];
    int x=atoi(argv[2]);
	int nextprime = simp_prog_1 (host,x);
    printf("Next prime of %d is %d",x,nextprime);
exit (0);
}
